import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Metabook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-bg min-h-screen flex flex-col justify-between text-primmary w-screen`}
      >
        <main className="px-6 py-6">
          {children}
        </main>
        <footer className="flex px-6 py-2.5 items-center h-fit justify-between border-t border-border text-secondary">
          <h5 className="text-sm">© 2025 MetaBook</h5>
          <div>
            <ul className="flex gap-2.5">
              <li><a href="" className="text-sm">About</a></li>
              <li><a href="https://superheroapi.com/index.html" className="text-sm">API</a></li>
            </ul>
          </div>
        </footer>
      </body>
    </html>
  );
}
